name: eccapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

  # Firebase (MUST be under dependencies)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.3.4
  async: ^2.11.0

  # Other
  image_picker: ^1.1.2
  intl: ^0.18.1
  image: ^4.2.0    # <â€” add this for real compression on web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
